name: GUI
version: '1.0-SNAPSHOT'
main: org.kingdom.yd.gui.GUI
api-version: '1.20'
authors: [YD]
commands:
  menu:
  attendance:
    usage: /attendance <add|remove|list>
  level:
    usage: /level <add|remove|list>
